create table if not exists public.cimento_sevkler (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  tarih date not null,
  firma text not null,
  teslim_yeri text not null,
  arac_sayisi integer not null check (arac_sayisi > 0),
  toplam_tonaj numeric(12,2) not null check (toplam_tonaj > 0),
  notlar text
);

alter table public.cimento_sevkler enable row level security;

drop policy if exists "cimento_select_authenticated" on public.cimento_sevkler;
create policy "cimento_select_authenticated" on public.cimento_sevkler
for select to authenticated using (true);

drop policy if exists "cimento_insert_authenticated" on public.cimento_sevkler;
create policy "cimento_insert_authenticated" on public.cimento_sevkler
for insert to authenticated with check (true);

drop policy if exists "cimento_update_authenticated" on public.cimento_sevkler;
create policy "cimento_update_authenticated" on public.cimento_sevkler
for update to authenticated using (true) with check (true);

drop policy if exists "cimento_delete_authenticated" on public.cimento_sevkler;
create policy "cimento_delete_authenticated" on public.cimento_sevkler
for delete to authenticated using (true);

create index if not exists cimento_sevkler_tarih_idx on public.cimento_sevkler(tarih desc);
