(function(){
'use strict';
const $=id=>document.getElementById(id);
const TABLE='sozlesmeler';
let selectedId=null;
function db(){return typeof window.ensureDb==='function'?window.ensureDb():null}
function status(msg,error=false){let el=$('contractDeleteStatus');if(!el){el=document.createElement('div');el.id='contractDeleteStatus';el.style.cssText='margin-top:8px;font-size:13px;font-weight:700';$('contractSaveBtn')?.parentElement?.appendChild(el)}if(el){el.textContent=msg||'';el.style.color=error?'var(--danger,#b42318)':'var(--ok,#18794e)'}}
function ensureDeleteButton(){const save=$('contractSaveBtn');if(!save||$('contractDeleteBtn'))return;const del=document.createElement('button');del.id='contractDeleteBtn';del.type='button';del.className='btn btn-light';del.textContent='🗑️ Sözleşmeyi Sil';del.style.marginLeft='8px';del.style.display='none';save.insertAdjacentElement('afterend',del);del.addEventListener('click',removeSelected)}
function getSelectedId(){if(selectedId)return selectedId;if(window.selectedContractId)return window.selectedContractId;if(window.currentContractId)return window.currentContractId;return null}
async function removeSelected(){const id=getSelectedId();if(!id){status('Silmek için önce soldaki listeden bir sözleşme seç.',true);return}if(!confirm('Bu sözleşmeyi silmek istediğinize emin misiniz? Bu işlem geri alınamaz.'))return;const client=db();if(!client){status('Veritabanı bağlantısı yüklenemedi.',true);return}const del=$('contractDeleteBtn');if(del)del.disabled=true;status('Sözleşme siliniyor…');const{error}=await client.from(TABLE).delete().eq('id',id);if(del)del.disabled=false;if(error){status('Sözleşme silinemedi: '+error.message,true);return}selectedId=null;status('Sözleşme silindi.');if(del)del.style.display='none';if(typeof window.clearContractForm==='function')window.clearContractForm();if(typeof window.loadContracts==='function')await window.loadContracts();else if(typeof window.renderContracts==='function')await window.renderContracts()}
function watchSelection(){const list=$('contractsList');if(!list)return;list.addEventListener('click',e=>{const card=e.target.closest('[data-id],[data-contract-id],.contract-card');if(!card)return;const id=card.dataset.id||card.dataset.contractId||card.getAttribute('data-contract-id');setTimeout(()=>{selectedId=id||window.selectedContractId||window.currentContractId||null;const del=$('contractDeleteBtn');if(del)del.style.display=selectedId?'inline-flex':'none';status('')},80)},true)}
function init(){if(!$('contractsPage'))return;ensureDeleteButton();watchSelection();const newBtn=$('contractNewBtn');newBtn?.addEventListener('click',()=>{selectedId=null;const del=$('contractDeleteBtn');if(del)del.style.display='none';status('')});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(init,350),{once:true});else setTimeout(init,350);
})();