(function(){
'use strict';
const $=id=>document.getElementById(id);
const TABLE='sozlesmeler';
const db=()=>typeof window.ensureDb==='function'?window.ensureDb():null;

function addStyles(){
  if(!$('contractListDeleteStyles')){
    const s=document.createElement('style');s.id='contractListDeleteStyles';s.textContent=`#contractsList .contract-card-wrap{position:relative;margin-bottom:10px}#contractsList .contract-card-wrap>.contract-card{width:100%;margin:0;padding-right:58px}#contractsList .contract-list-delete{position:absolute;right:10px;top:50%;transform:translateY(-50%);z-index:3;width:36px;height:36px;border:1px solid rgba(190,40,40,.18);border-radius:10px;background:#fff0f0;color:#b42318;cursor:pointer;font-size:16px;display:flex;align-items:center;justify-content:center}#contractsList .contract-list-delete:hover{background:#ffe3e3}`;document.head.appendChild(s);
  }
  if(!$('shipmentFilterStyles')){
    const s=document.createElement('style');s.id='shipmentFilterStyles';s.textContent=`
      #shipmentQuickFilters{margin:14px 0 16px;padding:14px;border:1px solid rgba(103,52,189,.14);border-radius:14px;background:rgba(255,255,255,.48)}
      #shipmentQuickFilters .sqf-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px;flex-wrap:wrap}#shipmentQuickFilters .sqf-head strong{font-size:15px;color:var(--purple-dark,#4d2393)}
      #shipmentQuickFilters .sqf-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;align-items:end}#shipmentQuickFilters label{display:flex;flex-direction:column;gap:5px;font-size:12px;font-weight:800;color:var(--muted,#687181)}
      #shipmentQuickFilters select,#shipmentQuickFilters input{box-sizing:border-box;width:100%;height:42px;border:1px solid rgba(103,52,189,.20);border-radius:10px;background:rgba(255,255,255,.86);padding:0 10px;font:inherit;color:var(--ink,#202633)}
      #shipmentFilterResult{font-size:12px;font-weight:800;color:var(--purple-dark,#4d2393)}#shipmentQuickFilters .sqf-clear{justify-self:start;min-width:150px}
      #shipmentFilterExports{display:flex;gap:8px;flex-wrap:wrap;margin-top:12px;padding-top:12px;border-top:1px solid rgba(103,52,189,.12)}
      @media(max-width:800px){#shipmentQuickFilters .sqf-grid{grid-template-columns:1fr 1fr}}@media(max-width:520px){#shipmentQuickFilters .sqf-grid{grid-template-columns:1fr}#shipmentFilterExports .btn{flex:1}}
    `;document.head.appendChild(s);
  }
}
function hideDetailDelete(){const old=$('contractDeleteBtn');if(old)old.remove()}
function cardId(card){const m=(card?.getAttribute('onclick')||'').match(/selectContract\((\d+)\)/);return m?m[1]:null}
async function deleteContract(id,btn){if(!id||!confirm('Bu sözleşmeyi silmek istediğinize emin misiniz? Bu işlem geri alınamaz.'))return;const client=db();if(!client){alert('Veritabanı bağlantısı yüklenemedi.');return}if(btn)btn.disabled=true;const {error}=await client.from(TABLE).delete().eq('id',id);if(btn)btn.disabled=false;if(error){alert('Sözleşme silinemedi: '+error.message);return}if(typeof window.clearContractForm==='function')window.clearContractForm();if(typeof window.loadContracts==='function')await window.loadContracts();decorateCards()}
function decorateCards(){hideDetailDelete();const list=$('contractsList');if(!list)return;[...list.querySelectorAll('.contract-card')].forEach(card=>{if(card.closest('.contract-card-wrap'))return;const id=cardId(card);if(!id)return;const wrap=document.createElement('div');wrap.className='contract-card-wrap';card.parentNode.insertBefore(wrap,card);wrap.appendChild(card);const del=document.createElement('button');del.type='button';del.className='contract-list-delete';del.title='Sözleşmeyi Sil';del.setAttribute('aria-label','Sözleşmeyi Sil');del.textContent='🗑️';del.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();deleteContract(id,del)});wrap.appendChild(del)})}
function observeList(){const list=$('contractsList');if(!list||list.dataset.deleteObserver==='1')return;list.dataset.deleteObserver='1';new MutationObserver(()=>requestAnimationFrame(decorateCards)).observe(list,{childList:true,subtree:false})}

const norm=v=>String(v||'').trim().toLocaleLowerCase('tr-TR').replace(/\s+/g,' ');
function betonBlock(){const box=$('recordsCombinedView');if(!box)return null;return [...box.querySelectorAll('.rc-block')].find(x=>/Beton Sevkiyatları/i.test(x.querySelector('h3')?.textContent||''))||null}
function uniqueFromRows(rows,index){return [...new Set(rows.map(r=>(r.children[index]?.textContent||'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'tr'))}
function esc(v){return String(v).replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;').replace(/>/g,'&gt;')}
function fillSelect(select,values,label){if(!select)return;const current=select.value;select.innerHTML=`<option value="">Tüm ${label}</option>`+values.map(v=>`<option value="${esc(v)}">${v}</option>`).join('');if([...select.options].some(o=>o.value===current))select.value=current}
function rowDate(row){const t=(row.children[1]?.textContent||'').trim();let m=t.match(/(\d{2})\.(\d{2})\.(\d{4})/);if(m)return `${m[3]}-${m[2]}-${m[1]}`;m=t.match(/(\d{4})-(\d{2})-(\d{2})/);return m?m[0]:''}
function ensureShipmentFilters(){const block=betonBlock();if(!block)return false;let panel=$('shipmentQuickFilters');if(!panel){panel=document.createElement('div');panel.id='shipmentQuickFilters';panel.innerHTML=`<div class="sqf-head"><strong>🔎 Sevkiyat Filtreleri</strong><span id="shipmentFilterResult"></span></div><div class="sqf-grid"><label>Firma<select id="shipmentFilterCompany"><option value="">Tüm Firmalar</option></select></label><label>Şantiye<select id="shipmentFilterSite"><option value="">Tüm Şantiyeler</option></select></label><label>Santral<select id="shipmentFilterPlant"><option value="">Tüm Santraller</option></select></label><label>Beton Sınıfı<select id="shipmentFilterConcrete"><option value="">Tüm Beton Sınıfları</option></select></label><label>Başlangıç Tarihi<input id="shipmentFilterStart" type="date"></label><label>Bitiş Tarihi<input id="shipmentFilterEnd" type="date"></label><button id="shipmentFilterClear" type="button" class="btn btn-light sqf-clear">Filtreleri Temizle</button></div><div id="shipmentFilterExports"><button id="shipmentFilterPdf" type="button" class="btn btn-light">PDF İndir</button><button id="shipmentFilterExcel" type="button" class="btn btn-light">Excel İndir</button><button id="shipmentFilterPrint" type="button" class="btn btn-light">Yazdır</button></div>`;block.insertBefore(panel,block.querySelector('.rc-table')||block.firstChild);['shipmentFilterCompany','shipmentFilterSite','shipmentFilterPlant','shipmentFilterConcrete','shipmentFilterStart','shipmentFilterEnd'].forEach(id=>$(id)?.addEventListener('change',applyShipmentFilters));$('shipmentFilterClear')?.addEventListener('click',()=>{['shipmentFilterCompany','shipmentFilterSite','shipmentFilterPlant','shipmentFilterConcrete','shipmentFilterStart','shipmentFilterEnd'].forEach(id=>{if($(id))$(id).value=''});applyShipmentFilters()});$('shipmentFilterPdf')?.addEventListener('click',exportFilteredPdf);$('shipmentFilterExcel')?.addEventListener('click',exportFilteredExcel);$('shipmentFilterPrint')?.addEventListener('click',printFiltered)}refreshShipmentFilterOptions();applyShipmentFilters();return true}
function refreshShipmentFilterOptions(){const block=betonBlock();if(!block)return;const rows=[...block.querySelectorAll('.rc-table tbody tr')].filter(r=>r.children.length>=9);fillSelect($('shipmentFilterCompany'),uniqueFromRows(rows,4),'Firmalar');fillSelect($('shipmentFilterSite'),uniqueFromRows(rows,5),'Şantiyeler');fillSelect($('shipmentFilterPlant'),uniqueFromRows(rows,3),'Santraller');fillSelect($('shipmentFilterConcrete'),uniqueFromRows(rows,6),'Beton Sınıfları')}
function parseM3(text){const raw=String(text||'').replace(/m³/gi,'').replace(/\+/g,'').replace(/\./g,'').replace(',','.').replace(/[^0-9.-]/g,'');const n=Number(raw);return Number.isFinite(n)?n:0}
function trNum(n){return Number(n||0).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})}
function filteredRows(){const block=betonBlock();if(!block)return[];return [...block.querySelectorAll('.rc-table tbody tr')].filter(r=>r.children.length>=9&&r.style.display!=='none')}
function filterSummary(){const parts=[];[['Firma','shipmentFilterCompany'],['Şantiye','shipmentFilterSite'],['Santral','shipmentFilterPlant'],['Beton','shipmentFilterConcrete']].forEach(([label,id])=>{if($(id)?.value)parts.push(`${label}: ${$(id).value}`)});if($('shipmentFilterStart')?.value)parts.push(`Başlangıç: ${$('shipmentFilterStart').value.split('-').reverse().join('.')}`);if($('shipmentFilterEnd')?.value)parts.push(`Bitiş: ${$('shipmentFilterEnd').value.split('-').reverse().join('.')}`);return parts.length?parts.join(' · '):'Tüm Sevkiyatlar'}
function exportData(){const rows=filteredRows();const data=rows.map((r,i)=>({No:i+1,Tarih:(r.children[1]?.textContent||'').trim(),Saat:(r.children[2]?.textContent||'').trim(),Santral:(r.children[3]?.textContent||'').trim(),Firma:(r.children[4]?.textContent||'').trim(),'Şantiye':(r.children[5]?.textContent||'').trim(),Beton:(r.children[6]?.textContent||'').trim(),Metraj:(r.children[7]?.textContent||'').trim(),Pompa:(r.children[8]?.textContent||'').trim()}));const total=rows.reduce((s,r)=>s+parseM3(r.children[7]?.textContent),0);return{rows,data,total}}
async function exportFilteredPdf(){const pack=exportData();if(!pack.rows.length){alert('Çıktı alınacak filtrelenmiş sevkiyat bulunmuyor.');return}if(!window.jspdf?.jsPDF){alert('PDF modülü yüklenemedi.');return}const{jsPDF}=window.jspdf,doc=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});let font='helvetica',text=v=>String(v??'');try{if(typeof window.preparePdfFont==='function'){const f=await window.preparePdfFont(doc);if(f){font=f.name||font;text=f.text||text}}}catch(e){}doc.setFont(font,'normal');doc.setFontSize(14);doc.text(text('Filtrelenmiş Beton Sevkiyatları'),14,14);doc.setFontSize(8);doc.text(text(filterSummary()),14,20,{maxWidth:265});doc.autoTable({head:[['No','Tarih','Saat','Santral','Firma','Şantiye','Beton','Metraj','Pompa'].map(text)],body:pack.data.map(x=>[x.No,x.Tarih,x.Saat,x.Santral,x.Firma,x['Şantiye'],x.Beton,x.Metraj,x.Pompa].map(text)),startY:25,styles:{font,fontSize:7},headStyles:{font,fillColor:[111,66,193]},margin:{left:14,right:14}});const y=(doc.lastAutoTable?.finalY||30)+8;doc.setFontSize(10);doc.text(text(`TOPLAM: ${pack.rows.length} sevkiyat · ${trNum(pack.total)} m³`),14,y);doc.save('Filtrelenmis-Beton-Sevkiyatlari.pdf')}
function exportFilteredExcel(){const pack=exportData();if(!pack.rows.length){alert('Çıktı alınacak filtrelenmiş sevkiyat bulunmuyor.');return}if(!window.XLSX){alert('Excel modülü yüklenemedi.');return}const rows=pack.data.map(x=>({...x,Metraj:Number(parseM3(x.Metraj))}));rows.push({No:'',Tarih:'',Saat:'',Santral:'',Firma:'TOPLAM','Şantiye':'',Beton:'',Metraj:pack.total,Pompa:''});const wb=XLSX.utils.book_new(),ws=XLSX.utils.json_to_sheet(rows);XLSX.utils.book_append_sheet(wb,ws,'Filtrelenmiş Sevkiyatlar');XLSX.writeFile(wb,'Filtrelenmis-Beton-Sevkiyatlari.xlsx')}
function printFiltered(){const pack=exportData();if(!pack.rows.length){alert('Yazdırılacak filtrelenmiş sevkiyat bulunmuyor.');return}const w=window.open('','_blank');if(!w)return;w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Filtrelenmiş Beton Sevkiyatları</title><style>body{font-family:Arial,sans-serif;padding:22px;color:#202633}h2{margin:0 0 4px}p{margin:0 0 16px;color:#687181;font-size:12px}table{width:100%;border-collapse:collapse;font-size:10px}th,td{border:1px solid #bbb;padding:6px;text-align:left}th{background:#6f42c1;color:white}.total{margin-top:12px;font-weight:bold;text-align:right}</style></head><body><h2>Filtrelenmiş Beton Sevkiyatları</h2><p>${esc(filterSummary())}</p><table><thead><tr><th>No</th><th>Tarih</th><th>Saat</th><th>Santral</th><th>Firma</th><th>Şantiye</th><th>Beton</th><th>Metraj</th><th>Pompa</th></tr></thead><tbody>${pack.data.map(x=>`<tr><td>${x.No}</td><td>${esc(x.Tarih)}</td><td>${esc(x.Saat)}</td><td>${esc(x.Santral)}</td><td>${esc(x.Firma)}</td><td>${esc(x['Şantiye'])}</td><td>${esc(x.Beton)}</td><td>${esc(x.Metraj)}</td><td>${esc(x.Pompa)}</td></tr>`).join('')}</tbody></table><div class="total">TOPLAM: ${pack.rows.length} sevkiyat · ${trNum(pack.total)} m³</div></body></html>`);w.document.close();w.focus();setTimeout(()=>w.print(),250)}
function applyShipmentFilters(){const block=betonBlock();if(!block)return;const company=norm($('shipmentFilterCompany')?.value),site=norm($('shipmentFilterSite')?.value),plant=norm($('shipmentFilterPlant')?.value),concrete=norm($('shipmentFilterConcrete')?.value),start=$('shipmentFilterStart')?.value||'',end=$('shipmentFilterEnd')?.value||'';const rows=[...block.querySelectorAll('.rc-table tbody tr')].filter(r=>r.children.length>=9);let count=0,total=0;rows.forEach(r=>{const d=rowDate(r);const ok=(!company||norm(r.children[4]?.textContent)===company)&&(!site||norm(r.children[5]?.textContent)===site)&&(!plant||norm(r.children[3]?.textContent)===plant)&&(!concrete||norm(r.children[6]?.textContent)===concrete)&&(!start||d>=start)&&(!end||d<=end);r.style.display=ok?'':'none';if(ok){count++;total+=parseM3(r.children[7]?.textContent)}});const result=$('shipmentFilterResult');if(result)result.textContent=`${count} sevkiyat · ${trNum(total)} m³`;const totalBox=block.querySelector('.rc-total');if(totalBox){totalBox.dataset.originalHtml=totalBox.dataset.originalHtml||totalBox.innerHTML;const active=company||site||plant||concrete||start||end;if(active)totalBox.innerHTML=`<span>FİLTRELENEN SEVKİYAT: ${count}</span><span>FİLTRELENEN BETON: ${trNum(total)} m³</span>`;else if(totalBox.dataset.originalHtml)totalBox.innerHTML=totalBox.dataset.originalHtml}}
function observeRecords(){const host=$('recordsPage');if(!host||host.dataset.shipmentFilterObserver==='1')return;host.dataset.shipmentFilterObserver='1';let timer=null;new MutationObserver(()=>{clearTimeout(timer);timer=setTimeout(ensureShipmentFilters,80)}).observe(host,{childList:true,subtree:true})}
function initFilters(){addStyles();observeRecords();ensureShipmentFilters();document.querySelector('[data-page="records"]')?.addEventListener('click',()=>setTimeout(ensureShipmentFilters,120))}
function init(){if($('contractsPage')){addStyles();hideDetailDelete();decorateCards();observeList()}initFilters()}
let tries=0;const timer=setInterval(()=>{tries++;init();if(tries>60)clearInterval(timer)},250);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();